#define sexp_so_extension ".dylib"
#define sexp_default_module_path "/Users/yam/pixelzoo/chibi//lib:/Users/yam/pixelzoo/chibi//lib/chibi"
#define sexp_platform "macosx"
#define sexp_version ""
#define sexp_release_name ""
