// generated by perl/makepoly.pl

#define PolymerDetachLinkDir(TYPE,BUILDER,X,Y,DIR,REV,FLAGVAR,REVFLAGVAR,DIRVAR,REVDIRVAR,RATE)\
  {\
      <rate (RATE/3)>;\
      loc orig(0,0);\
      loc nbr(X,Y);\
      if orig.FLAGVAR = 1;\
      if orig.DIRVAR = DIR;\
      if nbr.type != TYPE;\
      if nbr.type != BUILDER;\
      do orig.FLAGVAR = 0;\
  }\
  {\
      <rate (RATE/3)>;\
      loc orig(0,0);\
      loc nbr(X,Y);\
      if orig.FLAGVAR = 1;\
      if orig.DIRVAR = DIR;\
      if nbr.type = TYPE;\
      if nbr.REVFLAGVAR != 1;\
      do orig.FLAGVAR = 0;\
  }\
  {\
      <rate (RATE/3)>;\
      loc orig(0,0);\
      loc nbr(X,Y);\
      if orig.FLAGVAR = 1;\
      if orig.DIRVAR = DIR;\
      if nbr.type = TYPE;\
      if nbr.REVFLAGVAR = 1;\
      if nbr.REVDIRVAR != REV;\
      do orig.FLAGVAR = 0;\
  }\

#define PolymerDetachDir(TYPE,BUILDER,X,Y,DIR,REV,RATE)\
PolymerDetachLinkDir(TYPE,BUILDER,X,Y,DIR,REV,lflag,rflag,ldir,rdir,(RATE/2));\
PolymerDetachLinkDir(TYPE,BUILDER,X,Y,DIR,REV,rflag,lflag,rdir,ldir,(RATE/2));\

#define PolymerDetach(TYPE,BUILDER,RATE)\
PolymerDetachDir(TYPE,BUILDER,0,-1,0,4,(RATE/8));\
PolymerDetachDir(TYPE,BUILDER,+1,-1,1,5,(RATE/8));\
PolymerDetachDir(TYPE,BUILDER,+1,0,2,6,(RATE/8));\
PolymerDetachDir(TYPE,BUILDER,+1,+1,3,7,(RATE/8));\
PolymerDetachDir(TYPE,BUILDER,0,+1,4,0,(RATE/8));\
PolymerDetachDir(TYPE,BUILDER,-1,+1,5,1,(RATE/8));\
PolymerDetachDir(TYPE,BUILDER,-1,0,6,2,(RATE/8));\
PolymerDetachDir(TYPE,BUILDER,-1,-1,7,3,(RATE/8));\

#define PolymerDrain(RATE)\
  {\
      <rate RATE>;\
      loc orig(0,0);\
      if orig.lflag = 0;\
      if orig.rflag = 0;\
      do orig = empty;\
  }\

#define PolymerMidStepDir(TYPE,LX,LY,OLDLDIR,OLDLREV,RX,RY,OLDRDIR,OLDRREV,DX,DY,NEWLDIR,NEWLREV,NEWRDIR,NEWRREV,RATE)\
  {\
    <rate RATE>;\
    loc orig(0,0);\
    loc next(DX,DY);\
    loc left(LX,LY);\
    loc right(RX,RY);\
    if orig.lflag = 1;\
    if orig.ldir = OLDLDIR;\
    if left.type = TYPE;\
    if left.rflag = 1;\
    if left.rdir = OLDLREV;\
    if orig.rflag = 1;\
    if orig.rdir = OLDRDIR;\
    if right.type = TYPE;\
    if right.lflag = 1;\
    if right.ldir = OLDRREV;\
    if next.type = empty;\
    do next = orig;\
    do next.ldir = NEWLDIR;\
    do next.rdir = NEWRDIR;\
    do left.rdir = NEWLREV;\
    do right.ldir = NEWRREV;\
    do orig = empty;\
  }\

#define PolymerLeftmostStepDir(TYPE,RX,RY,OLDRDIR,OLDRREV,DX,DY,NEWRDIR,NEWRREV,RATE)\
  {\
    <rate RATE>;\
    loc orig(0,0);\
    loc next(DX,DY);\
    loc right(RX,RY);\
    if orig.lflag = 0;\
    if orig.rflag = 1;\
    if orig.rdir = OLDRDIR;\
    if right.type = TYPE;\
    if right.lflag = 1;\
    if right.ldir = OLDRREV;\
    if next.type = empty;\
    do next = orig;\
    do next.rdir = NEWRDIR;\
    do right.ldir = NEWRREV;\
    do orig = empty;\
  }\

#define PolymerRightmostStepDir(TYPE,LX,LY,OLDLDIR,OLDLREV,DX,DY,NEWLDIR,NEWLREV,RATE)\
  {\
    <rate RATE>;\
    loc orig(0,0);\
    loc next(DX,DY);\
    loc left(LX,LY);\
    if orig.rflag = 0;\
    if orig.lflag = 1;\
    if orig.ldir = OLDLDIR;\
    if left.type = TYPE;\
    if left.rflag = 1;\
    if left.rdir = OLDLREV;\
    if next.type = empty;\
    do next = orig;\
    do next.ldir = NEWLDIR;\
    do left.rdir = NEWLREV;\
    do orig = empty;\
  }\

#define PolymerStep(TYPE,BUILDER,RATE)\
PolymerLeftmostStep(TYPE,(RATE/3));\
PolymerRightmostStep(TYPE,(RATE/3));\
PolymerMidStep(TYPE,(RATE/3));\
PolymerDetach(TYPE,BUILDER,(RATE/30));\
PolymerDrain((RATE/30));\


#define PolymerMidStep(TYPE,RATE)\
PolymerMidStepDir(TYPE,-1,-1,7,3,-1,0,6,2,0,-1,6,2,5,1,(RATE/56));\
PolymerMidStepDir(TYPE,-1,-1,7,3,-1,1,5,1,-1,0,0,4,4,0,(RATE/56));\
PolymerMidStepDir(TYPE,-1,-1,7,3,0,-1,0,4,-1,0,0,4,1,5,(RATE/56));\
PolymerMidStepDir(TYPE,-1,-1,7,3,0,1,4,0,-1,0,0,4,3,7,(RATE/56));\
PolymerMidStepDir(TYPE,-1,-1,7,3,1,-1,1,5,0,-1,6,2,2,6,(RATE/56));\
PolymerMidStepDir(TYPE,-1,-1,7,3,1,0,2,6,0,-1,6,2,3,7,(RATE/56));\
PolymerMidStepDir(TYPE,-1,0,6,2,-1,-1,7,3,0,-1,5,1,6,2,(RATE/56));\
PolymerMidStepDir(TYPE,-1,0,6,2,-1,1,5,1,0,1,7,3,6,2,(RATE/56));\
PolymerMidStepDir(TYPE,-1,0,6,2,0,-1,0,4,-1,-1,4,0,2,6,(RATE/56));\
PolymerMidStepDir(TYPE,-1,0,6,2,0,1,4,0,-1,1,0,4,2,6,(RATE/56));\
PolymerMidStepDir(TYPE,-1,0,6,2,1,-1,1,5,0,-1,5,1,2,6,(RATE/56));\
PolymerMidStepDir(TYPE,-1,0,6,2,1,0,2,6,0,-1,5,1,3,7,(RATE/56));\
PolymerMidStepDir(TYPE,-1,0,6,2,1,0,2,6,0,1,7,3,1,5,(RATE/56));\
PolymerMidStepDir(TYPE,-1,0,6,2,1,1,3,7,0,1,7,3,2,6,(RATE/56));\
PolymerMidStepDir(TYPE,-1,1,5,1,-1,-1,7,3,-1,0,4,0,0,4,(RATE/56));\
PolymerMidStepDir(TYPE,-1,1,5,1,-1,0,6,2,0,1,6,2,7,3,(RATE/56));\
PolymerMidStepDir(TYPE,-1,1,5,1,0,-1,0,4,-1,0,4,0,1,5,(RATE/56));\
PolymerMidStepDir(TYPE,-1,1,5,1,0,1,4,0,-1,0,4,0,3,7,(RATE/56));\
PolymerMidStepDir(TYPE,-1,1,5,1,1,0,2,6,0,1,6,2,1,5,(RATE/56));\
PolymerMidStepDir(TYPE,-1,1,5,1,1,1,3,7,0,1,6,2,2,6,(RATE/56));\
PolymerMidStepDir(TYPE,0,-1,0,4,-1,-1,7,3,-1,0,1,5,0,4,(RATE/56));\
PolymerMidStepDir(TYPE,0,-1,0,4,-1,0,6,2,-1,-1,2,6,4,0,(RATE/56));\
PolymerMidStepDir(TYPE,0,-1,0,4,-1,1,5,1,-1,0,1,5,4,0,(RATE/56));\
PolymerMidStepDir(TYPE,0,-1,0,4,0,1,4,0,-1,0,1,5,3,7,(RATE/56));\
PolymerMidStepDir(TYPE,0,-1,0,4,0,1,4,0,1,0,7,3,5,1,(RATE/56));\
PolymerMidStepDir(TYPE,0,-1,0,4,1,-1,1,5,1,0,7,3,0,4,(RATE/56));\
PolymerMidStepDir(TYPE,0,-1,0,4,1,0,2,6,1,-1,6,2,4,0,(RATE/56));\
PolymerMidStepDir(TYPE,0,-1,0,4,1,1,3,7,1,0,7,3,4,0,(RATE/56));\
PolymerMidStepDir(TYPE,0,1,4,0,-1,-1,7,3,-1,0,3,7,0,4,(RATE/56));\
PolymerMidStepDir(TYPE,0,1,4,0,-1,0,6,2,-1,1,2,6,0,4,(RATE/56));\
PolymerMidStepDir(TYPE,0,1,4,0,-1,1,5,1,-1,0,3,7,4,0,(RATE/56));\
PolymerMidStepDir(TYPE,0,1,4,0,0,-1,0,4,-1,0,3,7,1,5,(RATE/56));\
PolymerMidStepDir(TYPE,0,1,4,0,0,-1,0,4,1,0,5,1,7,3,(RATE/56));\
PolymerMidStepDir(TYPE,0,1,4,0,1,-1,1,5,1,0,5,1,0,4,(RATE/56));\
PolymerMidStepDir(TYPE,0,1,4,0,1,0,2,6,1,1,6,2,0,4,(RATE/56));\
PolymerMidStepDir(TYPE,0,1,4,0,1,1,3,7,1,0,5,1,4,0,(RATE/56));\
PolymerMidStepDir(TYPE,1,-1,1,5,-1,-1,7,3,0,-1,2,6,6,2,(RATE/56));\
PolymerMidStepDir(TYPE,1,-1,1,5,-1,0,6,2,0,-1,2,6,5,1,(RATE/56));\
PolymerMidStepDir(TYPE,1,-1,1,5,0,-1,0,4,1,0,0,4,7,3,(RATE/56));\
PolymerMidStepDir(TYPE,1,-1,1,5,0,1,4,0,1,0,0,4,5,1,(RATE/56));\
PolymerMidStepDir(TYPE,1,-1,1,5,1,0,2,6,0,-1,2,6,3,7,(RATE/56));\
PolymerMidStepDir(TYPE,1,-1,1,5,1,1,3,7,1,0,0,4,4,0,(RATE/56));\
PolymerMidStepDir(TYPE,1,0,2,6,-1,-1,7,3,0,-1,3,7,6,2,(RATE/56));\
PolymerMidStepDir(TYPE,1,0,2,6,-1,0,6,2,0,-1,3,7,5,1,(RATE/56));\
PolymerMidStepDir(TYPE,1,0,2,6,-1,0,6,2,0,1,1,5,7,3,(RATE/56));\
PolymerMidStepDir(TYPE,1,0,2,6,-1,1,5,1,0,1,1,5,6,2,(RATE/56));\
PolymerMidStepDir(TYPE,1,0,2,6,0,-1,0,4,1,-1,4,0,6,2,(RATE/56));\
PolymerMidStepDir(TYPE,1,0,2,6,0,1,4,0,1,1,0,4,6,2,(RATE/56));\
PolymerMidStepDir(TYPE,1,0,2,6,1,-1,1,5,0,-1,3,7,2,6,(RATE/56));\
PolymerMidStepDir(TYPE,1,0,2,6,1,1,3,7,0,1,1,5,2,6,(RATE/56));\
PolymerMidStepDir(TYPE,1,1,3,7,-1,0,6,2,0,1,2,6,7,3,(RATE/56));\
PolymerMidStepDir(TYPE,1,1,3,7,-1,1,5,1,0,1,2,6,6,2,(RATE/56));\
PolymerMidStepDir(TYPE,1,1,3,7,0,-1,0,4,1,0,4,0,7,3,(RATE/56));\
PolymerMidStepDir(TYPE,1,1,3,7,0,1,4,0,1,0,4,0,5,1,(RATE/56));\
PolymerMidStepDir(TYPE,1,1,3,7,1,-1,1,5,1,0,4,0,0,4,(RATE/56));\
PolymerMidStepDir(TYPE,1,1,3,7,1,0,2,6,0,1,2,6,1,5,(RATE/56));\

#define PolymerLeftmostStep(TYPE,RATE)\
PolymerLeftmostStepDir(TYPE,-1,-1,7,3,-1,0,0,4,(RATE/24));\
PolymerLeftmostStepDir(TYPE,-1,-1,7,3,0,-1,6,2,(RATE/24));\
PolymerLeftmostStepDir(TYPE,-1,0,6,2,-1,-1,4,0,(RATE/24));\
PolymerLeftmostStepDir(TYPE,-1,0,6,2,-1,1,0,4,(RATE/24));\
PolymerLeftmostStepDir(TYPE,-1,0,6,2,0,-1,5,1,(RATE/24));\
PolymerLeftmostStepDir(TYPE,-1,0,6,2,0,1,7,3,(RATE/24));\
PolymerLeftmostStepDir(TYPE,-1,1,5,1,-1,0,4,0,(RATE/24));\
PolymerLeftmostStepDir(TYPE,-1,1,5,1,0,1,6,2,(RATE/24));\
PolymerLeftmostStepDir(TYPE,0,-1,0,4,-1,-1,2,6,(RATE/24));\
PolymerLeftmostStepDir(TYPE,0,-1,0,4,-1,0,1,5,(RATE/24));\
PolymerLeftmostStepDir(TYPE,0,-1,0,4,1,-1,6,2,(RATE/24));\
PolymerLeftmostStepDir(TYPE,0,-1,0,4,1,0,7,3,(RATE/24));\
PolymerLeftmostStepDir(TYPE,0,1,4,0,-1,0,3,7,(RATE/24));\
PolymerLeftmostStepDir(TYPE,0,1,4,0,-1,1,2,6,(RATE/24));\
PolymerLeftmostStepDir(TYPE,0,1,4,0,1,0,5,1,(RATE/24));\
PolymerLeftmostStepDir(TYPE,0,1,4,0,1,1,6,2,(RATE/24));\
PolymerLeftmostStepDir(TYPE,1,-1,1,5,0,-1,2,6,(RATE/24));\
PolymerLeftmostStepDir(TYPE,1,-1,1,5,1,0,0,4,(RATE/24));\
PolymerLeftmostStepDir(TYPE,1,0,2,6,0,-1,3,7,(RATE/24));\
PolymerLeftmostStepDir(TYPE,1,0,2,6,0,1,1,5,(RATE/24));\
PolymerLeftmostStepDir(TYPE,1,0,2,6,1,-1,4,0,(RATE/24));\
PolymerLeftmostStepDir(TYPE,1,0,2,6,1,1,0,4,(RATE/24));\
PolymerLeftmostStepDir(TYPE,1,1,3,7,0,1,2,6,(RATE/24));\
PolymerLeftmostStepDir(TYPE,1,1,3,7,1,0,4,0,(RATE/24));\

#define PolymerRightmostStep(TYPE,RATE)\
PolymerRightmostStepDir(TYPE,-1,-1,7,3,-1,0,0,4,(RATE/24));\
PolymerRightmostStepDir(TYPE,-1,-1,7,3,0,-1,6,2,(RATE/24));\
PolymerRightmostStepDir(TYPE,-1,0,6,2,-1,-1,4,0,(RATE/24));\
PolymerRightmostStepDir(TYPE,-1,0,6,2,-1,1,0,4,(RATE/24));\
PolymerRightmostStepDir(TYPE,-1,0,6,2,0,-1,5,1,(RATE/24));\
PolymerRightmostStepDir(TYPE,-1,0,6,2,0,1,7,3,(RATE/24));\
PolymerRightmostStepDir(TYPE,-1,1,5,1,-1,0,4,0,(RATE/24));\
PolymerRightmostStepDir(TYPE,-1,1,5,1,0,1,6,2,(RATE/24));\
PolymerRightmostStepDir(TYPE,0,-1,0,4,-1,-1,2,6,(RATE/24));\
PolymerRightmostStepDir(TYPE,0,-1,0,4,-1,0,1,5,(RATE/24));\
PolymerRightmostStepDir(TYPE,0,-1,0,4,1,-1,6,2,(RATE/24));\
PolymerRightmostStepDir(TYPE,0,-1,0,4,1,0,7,3,(RATE/24));\
PolymerRightmostStepDir(TYPE,0,1,4,0,-1,0,3,7,(RATE/24));\
PolymerRightmostStepDir(TYPE,0,1,4,0,-1,1,2,6,(RATE/24));\
PolymerRightmostStepDir(TYPE,0,1,4,0,1,0,5,1,(RATE/24));\
PolymerRightmostStepDir(TYPE,0,1,4,0,1,1,6,2,(RATE/24));\
PolymerRightmostStepDir(TYPE,1,-1,1,5,0,-1,2,6,(RATE/24));\
PolymerRightmostStepDir(TYPE,1,-1,1,5,1,0,0,4,(RATE/24));\
PolymerRightmostStepDir(TYPE,1,0,2,6,0,-1,3,7,(RATE/24));\
PolymerRightmostStepDir(TYPE,1,0,2,6,0,1,1,5,(RATE/24));\
PolymerRightmostStepDir(TYPE,1,0,2,6,1,-1,4,0,(RATE/24));\
PolymerRightmostStepDir(TYPE,1,0,2,6,1,1,0,4,(RATE/24));\
PolymerRightmostStepDir(TYPE,1,1,3,7,0,1,2,6,(RATE/24));\
PolymerRightmostStepDir(TYPE,1,1,3,7,1,0,4,0,(RATE/24));\

